variables:
  PYTHON3_IMAGE: python:alpine

stages:
  - syntax

PyCodeStyle:
  image: $PYTHON3_IMAGE
  stage: syntaxe
  script:
    - pip install pycodestyle
    - pycodestyle app.py

Pylint:
  image: $PYTHON3_IMAGE
  stage: syntax
  script:
 - pip install pylint
 - pylint app.py